[connections.snowflake]
"account" = "NCXKOLM-UPSOCIATIVE"
"user" = "NNAVARRETE"
"password" = "Ups2905."
"role" = "US_INGENIERO_DATOS"
"warehouse" = "US_LOAD_WH"
"database" = "DEMOS_DB"
"schema" = "RAW"